# Session 1 — NUMPY

In [19]:
import numpy as np


normal_list= [1,2,3,4,5]
numpy_array= np.array([1,2,3,4,5])

print(f"Normal list : {normal_list}")
print(f"array : {numpy_array}")
print(f"type : {type(numpy_array)}")

# ---- Kyun NumPy? ----
# List pe math nahi hota directly
print(normal_list * 2)

print(f"Array * 2 : {numpy_array *2}")


marks = np.array([85, 92, 78, 90, 88, 76, 95, 82])
print(f"\n-----Marks Analysis-----")
print(f"Shape : {marks.shape}")           #no. of elements
print(f"Mean : {marks.mean()}")
print(f"Max : {marks.max()}")
print(f"Std : {marks.std():.3f}")
print(f" Sum : {marks.sum()}")

Normal list : [1, 2, 3, 4, 5]
array : [1 2 3 4 5]
type : <class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Array * 2 : [ 2  4  6  8 10]

-----Marks Analysis-----
Shape : (8,)
Mean : 85.75
Max : 95
Std : 6.300
 Sum : 686


2 D array matrix

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Matrix:\n{matrix}")
print(f"Shape : {matrix.shape}")
print(f"row 1 : {matrix[0]}")
print(f"column 1 : {matrix[:,0]}")
print(f"element : {matrix[1][2]}")


#filtering
marks = np.array([85, 45, 92, 38, 78, 55, 91, 42])

passed=marks[marks >=60]
failed=marks[marks<60]
print(f"\nAll marks : {marks}")
print(f"Passed    : {passed}")
print(f"Failed    : {failed}")
print(f"Pass      : {len(passed)/len(marks) *100:.2f}%")



#RandomArray

random_data = np.random.randint(1,100,size =10)
print(f"random_data : {random_data}")
print(f"Mean        : {random_data.mean()}")




# 
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)   # 2 rows, 3 columns
print(f"\nOriginal : {arr}")
print(f"Reshaped :\n{reshaped}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape : (3, 3)
row 1 : [1 2 3]
column 1 : [1 4 7]
element : 6

All marks : [85 45 92 38 78 55 91 42]
Passed    : [85 92 78 91]
Failed    : [45 38 55 42]
Pass      : 50.00%
random_data : [46 97 93  4  5 17 98 32 80 36]
Mean        : 50.8

Original : [1 2 3 4 5 6]
Reshaped :
[[1 2 3]
 [4 5 6]]
